name: 🐛 Bug Report
description: Report a bug (human review)
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.

  - type: input
    id: integration
    attributes:
      label: Integration
      description: Which integration is affected?
      placeholder: e.g., HAIMish
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any relevant error messages or logs
      render: shell

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      placeholder: e.g., 2024.12.0

  - type: input
    id: integration-version
    attributes:
      label: Integration Version
      placeholder: e.g., v1.1.0
